- name: install podman
  ansible.builtin.package:
    name: podman
- name: enable auto update
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    enabled: true
    state: started
- name: configure containers subuids
  ansible.builtin.copy:
    dest: /etc/subuid
    content: |
      containers:2147483647:2147483648
- name: configure containers subgids
  ansible.builtin.copy:
    dest: /etc/subgid
    content: |
      containers:2147483647:2147483648
